import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* FIX: Set main to flex, ensure it takes full height. */}
        <main className="min-h-screen flex flex-col items-center bg-gradient-to-b from-gray-950 via-gray-900 to-black text-white relative overflow-hidden">
          {/* ... Background effects ... */}
          
          {/* FIX: This wrapper MUST take up the full available space (flex-1) 
                     and have padding at the bottom (pb-16) to clear the fixed footer. */}
          <div className='relative z-50 w-full flex-1 pb-16'> 
            {children}
          </div>
          
          {/* FIX: Footer remains fixed */}
          <footer className="fixed bottom-6 text-sm text-gray-500 w-full text-center">
            © {new Date().getFullYear()} ConverzAI (Gemini Clone) | Built by Shubhi Srivastava
          </footer>
        </main>
      </body>
    </html>
  );
}
