import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-screen w-full flex flex-col items-center bg-gradient-to-b from-gray-950 via-gray-900 to-black text-white relative overflow-hidden">
          {/* Background effects */}
          <div className="absolute inset-0 pointer-events-none z-0 h-[80vh]">
            <div className="absolute -top-40 -left-40 w-96 h-96 bg-blue-500/30 rounded-full blur-3xl animate-pulse"></div>
            <div className="absolute -bottom-40 -right-40 w-96 h-96 bg-purple-500/30 rounded-full blur-3xl animate-pulse"></div>
          </div>

          {/* Main content area (takes full height, no scroll clipping) */}
          <div className="relative z-10 flex-1 w-full">
            {children}
          </div>

          {/* Footer (still visible, doesn't push layout up) */}
          <footer className="fixed bottom-2 text-xs text-gray-500 w-full text-center z-20">
            © {new Date().getFullYear()} ConverzAI (Gemini Clone) | Built by Shubhi Srivastava
          </footer>
        </main>


      </body>
    </html>
  );
}
